# ワークフローの名前
name: Daily Trend Summary

# ワークフローが実行されるトリガー
on:
  # スケジュール実行
  schedule:
    # JSTの午前8時 (UTCの前日23時) に毎日実行します。
    # 元の '0 11 * * *' はUTCの午前11時 (JSTの午後8時) でした。
    - cron: '0 23 * * *'
  
  # 手動実行も可能にする
  workflow_dispatch:

# 実行されるジョブ
jobs:
  build:
    # ubuntuの最新バージョンで実行
    runs-on: ubuntu-latest

    # ジョブのステップ
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 3系の最新版を使用

      # 3. 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. メインスクリプトの実行
      - name: Run daily summary script
        env:
          # GitHub Secretsから環境変数を設定
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: poetry run python main.py
